---
server.port: 8080
server.contextPath: /oms
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://192.168.1.77:3306/oms
    username: axis
    password: qwas143$AQZDEWSX
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

