---
server.port: 8080
server.contextPath: /oms
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://development.cjxp2kswevxt.us-west-2.rds.amazonaws.com:3306/oms
    username: axisgroup
    password: qwas143$AQZDEWSX
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 2
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

